services:
    phlexible_media_manager.doctrine.folder_usage_manager:
        class: Phlexible\Bundle\MediaManagerBundle\Usage\FolderUsageManager
        arguments: [@doctrine.orm.entity_manager]

    phlexible_media_manager.doctrine.file_usage_manager:
        class: Phlexible\Bundle\MediaManagerBundle\Usage\FileUsageManager
        arguments: [@doctrine.orm.entity_manager]
