services:
    phlexible_element.doctrine.element_manager:
        class: Phlexible\Bundle\ElementBundle\Doctrine\ElementManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher, @phlexible_message.message_poster]

    phlexible_element.doctrine.element_version_manager:
        class: Phlexible\Bundle\ElementBundle\Doctrine\ElementVersionManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher, @phlexible_message.message_poster]

    phlexible_element.doctrine.element_source_manager:
        class: Phlexible\Bundle\ElementBundle\Doctrine\ElementSourceManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher, @phlexible_message.message_poster]

    phlexible_element.doctrine.element_structure_manager:
        class: Phlexible\Bundle\ElementBundle\Doctrine\ElementStructureManager
        public: false
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_element.doctrine.element_structure_loader
            - @phlexible_elementtype.field.registry
            - @phlexible_element.link_extractor

    phlexible_element.doctrine.element_structure_loader:
        class: Phlexible\Bundle\ElementBundle\Doctrine\ElementStructureLoader
        public: false
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_elementtype.field.registry

    phlexible_element.doctrine.element_lock_manager:
        class: Phlexible\Bundle\ElementBundle\Doctrine\ElementLockManager
        public: false
        arguments: [@doctrine.orm.entity_manager]

    phlexible_element.doctrine.element_history_manager:
        class: Phlexible\Bundle\ElementBundle\Doctrine\ElementHistoryManager
        public: false
        arguments: [@doctrine.orm.entity_manager]
