services:
    phlexible_user.doctrine.user_manager:
        class: Phlexible\Bundle\UserBundle\Doctrine\UserManager
        public: false
        arguments:
            - "@security.encoder_factory"
            - "@fos_user.util.username_canonicalizer"
            - "@fos_user.util.email_canonicalizer"
            - "@fos_user.entity_manager"
            - "%fos_user.model.user.class%"
            - "@phlexible_user.successor_service"
            - "@event_dispatcher"
            - "%phlexible_user.user.system_user_id%"
            - "%phlexible_user.group.everyone_group_id%"

    phlexible_user.doctrine.group_manager:
        class: Phlexible\Bundle\UserBundle\Doctrine\GroupManager
        public: false
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "%phlexible_user.group.class%"
            - "%phlexible_user.group.everyone_group_id%"
