services:
    phlexible_tree.pattern_resolver:
        class: Phlexible\Bundle\TreeBundle\Pattern\PatternResolver
        arguments: [@translator, %phlexible_tree.patterns%, %phlexible_gui.project.title%]

    phlexible_tree.tree_manager:
        class: Phlexible\Bundle\TreeBundle\Tree\TreeManager
        arguments: [@phlexible_siteroot.siteroot_manager, @phlexible_tree.tree_factory]

    phlexible_tree.node_serializer:
        class: Phlexible\Bundle\TreeBundle\Tree\Serializer\NodeSerializer
        arguments:
            - @phlexible_element.element_service
            - @phlexible_element.icon_resolver
            - @phlexible_tree.state_manager
            - @phlexible_access_control.permissions
            - @security.authorization_checker

    phlexible_tree.router.handler.default:
        class: Phlexible\Bundle\TreeBundle\Router\Handler\DefaultHandler
        arguments:
            - @logger
            - @phlexible_tree.content_tree_manager
            - @phlexible_siteroot.siteroot_request_matcher
            - %phlexible_cms.languages.available%
            - %phlexible_cms.languages.default%
        tags:
            - {name: monolog.logger, channel: router}

    phlexible_tree.router:
        class: Phlexible\Bundle\TreeBundle\Router\TreeRouter
        arguments:
            - @router.request_context
            - @phlexible_tree.router.handler.default
            - @phlexible_tree.router.handler.default
            - ""
            - @event_dispatcher
        tags:
            - {name: monolog.logger, channel: router}
            - {name: router, priority: 100}

    phlexible_tree.node_hasher:
        class: Phlexible\Bundle\TreeBundle\Tree\NodeHasher
        arguments: [@phlexible_element.element_hasher]

    # access control permission providers
    phlexible_tree.permission_provider:
        class: Phlexible\Bundle\TreeBundle\AccessControl\TreePermissionProvider
        public: false
        tags:
            - {name: phlexible_access_control.permission}

    # event listeners
    phlexible_tree.listener.apply_successor:
        class: Phlexible\Bundle\TreeBundle\EventListener\ApplySuccessorListener
        arguments: [@doctrine.dbal.default_connection]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_tree.listener.exception:
        class: Phlexible\Bundle\TreeBundle\EventListener\ExceptionListener
        arguments:
            - @twig
            - @phlexible_element_renderer.configurator
            - @phlexible_tree.content_tree_manager
            - @logger
            - %kernel.debug%
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 999}

    # twig extensions
    phlexible_tree.twig.tree_extension:
        class: Phlexible\Bundle\TreeBundle\Twig\Extension\TreeExtension
        public: false
        arguments:
            - @phlexible_tree.content_tree_manager
            - @phlexible_tree.pattern_resolver
            - @request_stack
            - @security.authorization_checker
        tags:
            - {name: twig.extension}

    phlexible_tree.twig.url_extension:
        class: Phlexible\Bundle\TreeBundle\Twig\Extension\UrlExtension
        public: false
        arguments: [@router, @phlexible_tree.content_tree_manager.delegating]
        tags:
            - {name: twig.extension}
