services:
    phlexible_message.elastica.message_manager:
        class: Phlexible\Bundle\MessageBundle\Elastica\MessageManager
        public: false
        arguments:
            - "@phlexible_elastica.default_client"
