parameters:
    phlexible_meta_set.languages.default: en
    phlexible_meta_set.languages.available: en,de
    phlexible_meta_set.suggest.seperator: ,

services:
    phlexible_meta_set.option_resolver:
        class: Phlexible\Component\MetaSet\Model\OptionResolver

    # event listeners
    phlexible_meta_set.listener.get_config:
        class: Phlexible\Bundle\MetaSetBundle\EventListener\GetConfigListener
        arguments:
            - "@security.token_storage"
            - "%phlexible_meta_set.languages.default%"
            - "%phlexible_meta_set.languages.available%"
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}

    # role providers
    phlexible_meta_set.role_provider:
        class: Phlexible\Bundle\MetaSetBundle\RoleProvider\MetaSetRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
